CONFIG_ZMK_DISPLAY=y
# (opcional, mas ajuda a forçar um status screen)
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y

# Widgets úteis
CONFIG_ZMK_WIDGET_LAYER_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y

# RGB underglow (WS2812)
CONFIG_ZMK_RGB_UNDERGLOW=y

# Se o seu kit usa "ext power" para alimentar LEDs (muito comum em wireless)
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=y

# (opcional) brilho inicial
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=20

CONFIG_ZMK_ENCODER=y
CONFIG_EC11=y